time = 0:0.0001:20;
const = input('Enter Bit Depth of PCM Coding:');
part = -1:0.1:1;
codebook = -1:0.1:1.1;
msg = sin(time);
[indx,quants] = quantiz(msg,part,codebook);
subplot(3,1,1);
plot(time,msg);
title('Message Signal');
subplot(3,1,2);
plot(time,quants);
title('Quantized Signal');
y = uencode(quants,const);
ybin = dec2bin(y,const);
subplot(3,1,3);
plot(time,y);
title('PCM PLOT');